export enum ConfigurationKey {
  PORT = 'PORT',
  APP_STAGE = 'APP_STAGE',
  SENTRY_DNS_URL = 'SENTRY_DNS_URL',
  DATABASE_URL = 'DATABASE_URL',
  JWT_EXPIRY = 'JWT_EXPIRY',
  JWT_SECRET = 'JWT_SECRET',
  MAIL_ADDRESS = 'MAIL_ADDRESS',
  MAIL_PASSWORD = 'MAIL_PASSWORD',
  MINIO_ROOT_USER = 'MINIO_ROOT_USER',
  MINIO_ROOT_PASSWORD = 'MINIO_ROOT_PASSWORD',
  MINIO_BUCKET = 'MINIO_BUCKET',
  MINIO_ENDPOINT = 'MINIO_ENDPOINT',
  APP_NAME = 'APP_NAME',
  CLOUDINARY_API_NAME = 'CLOUDINARY_API_NAME',
  CLOUDINARY_API_KEY = 'CLOUDINARY_API_KEY',
  CLOUDINARY_API_SECRET = 'CLOUDINARY_API_SECRET',
}

export enum APP_STAGE {
  LOCAL = 'dev-local',
  PRODUCTION = 'prod',
  DEMO = 'demo',
}

export enum APP_MODULES {
  GLOBAL = 'app',
  AUTH = 'auth',
  MAIL = 'mail',
  ROLE = 'role',
  USER = 'user',
}
