name: Build and Run API

on:
  pull_request:
    branches: [production, main]

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build project
        run: yarn build

      - name: Run tests with coverage
        run: yarn test:cov

      - name: Start API with timeout
        run: |
          timeout 60s yarn start:prod &
          sleep 10
        env:
          APP_STAGE: ${{ secrets.APP_STAGE }}
          PORT: ${{ secrets.PORT }}
          SENTRY_DNS_URL: ${{ secrets.SENTRY_DNS_URL }}
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          FIREBASE_CLIENT_EMAIL: ${{ secrets.FIREBASE_CLIENT_EMAIL }}
          FIREBASE_PRIVATE_KEY: ${{ secrets.FIREBASE_PRIVATE_KEY }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          JWT_EXPIRY: ${{ secrets.JWT_EXPIRY }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          MAIL_ADDRESS: ${{ secrets.MAIL_ADDRESS }}
          MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
          MINIO_ROOT_USER: ${{ secrets.MINIO_ROOT_USER }}
          MINIO_ROOT_PASSWORD: ${{ secrets.MINIO_ROOT_PASSWORD }}
          MINIO_ENDPOINT: ${{ secrets.MINIO_ENDPOINT }}
          BUCKET: ${{ secrets.MINIO_BUCKET }}
          CLOUDINARY_API_NAME: ${{ secrets.CLOUDINARY_API_NAME }}
          CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
          CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}
          BASE_URL: ${{ secrets.BASE_URL }}
          RENDER_DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }}
          LOKI_HOST: ${{ secrets.LOKI_HOST }}
          LOKI_USERNAME: ${{ secrets.LOKI_USERNAME }}
          LOKI_BASIC_AUTH: ${{ secrets.LOKI_BASIC_AUTH }}
          REDIS_HOST: ${{ secrets.REDIS_HOST }}
          REDIS_PORT: ${{ secrets.REDIS_PORT }}
          REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
